title: Azienda Agricola Fea
email:
description: Fea Vini, Azienda Agricola Fea
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://feavini.com" # the base hostname & protocol for your site

markdown: kramdown

remote_theme: mmistakes/minimal-mistakes@4.19.2

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  vini:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: pages 
    values:
      layout: single
  # _portfolio
  - scope:
      path: ""
      type: vini 
    values:
      layout: single
      author_profile: false
      share: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
include: ["_pages"] 
