title: Azienda Agricola Fea di Valente Giuseppe
email: aziendafea@gmail.com
description: Fea Vini, Azienda Agricola Fea
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://feavini.com" # the base hostname & protocol for your site
repository: feavini/feavini.github.io
logo: "/assets/images/logo.png"
masthead_title: " "


# i18n
locale: "it-IT"
# languages: ["it", "en", "de"]
languages: ["it", "en"]
default_lang: "it"
exclude_from_localization: ["javascript", "images", "css", "assets", "Old Website"]
parallel_localization: true
  #index:
  # it: index.it.md
  # en: index.en.md
  # de: index.de.md
lang_vars: ['locale']


search: false 

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-facebook-square"
      url: "https://www.facebook.com/feavini/"


markdown: kramdown

# remote_theme: mmistakes/minimal-mistakes@4.24.0
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
github: [metadata]

collections:
  vini:
    output: true
    permalink: /:collection/:path/
    # Doesn't really work
    # sort_by: order

# Note: links top-right are found in _data/navigation.yml
defaults:
  # _pages
  - scope:
      path: ""
      type: pages 
    values:
      layout: single
      author_profile: false
  # _vini
  - scope:
      path: ""
      type: vini 
    values:
      layout: single
      author_profile: false
      share: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
include: ["_pages"] 
